# Generated by Django 5.0.14 on 2026-07-06 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffBiometricCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_hash', models.CharField(max_length=64, unique=True)),
                ('finger_used', models.CharField(blank=True, max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_credential', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_biometric_credentials',
            },
        ),
    ]
