# Generated by Django 5.0.14 on 2026-05-26 08:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('severity_default', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'incident_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('UNDER_REVIEW', 'Under Review'), ('DECIDED', 'Decided'), ('CLOSED', 'Closed')], default='REPORTED', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('CLEARED', 'Cleared'), ('WARNING', 'Formal Warning'), ('SUSPENSION', 'Suspension'), ('EXPULSION', 'Expulsion'), ('REFERRED', 'Referred to Police')], max_length=20)),
                ('description', models.TextField()),
                ('date_of_incident', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('outcome_notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_cases', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_cases', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinary_cases', to='students.student')),
                ('incident_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.incidenttype')),
            ],
            options={
                'db_table': 'disciplinary_cases',
                'ordering': ['-date_of_incident'],
            },
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cases.disciplinarycase')),
            ],
            options={
                'db_table': 'case_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cases/documents/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.disciplinarycase')),
            ],
            options={
                'db_table': 'case_documents',
            },
        ),
        migrations.AddIndex(
            model_name='disciplinarycase',
            index=models.Index(fields=['student', 'status'], name='disciplinar_student_c003ea_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinarycase',
            index=models.Index(fields=['status'], name='disciplinar_status_8b442f_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinarycase',
            index=models.Index(fields=['date_of_incident'], name='disciplinar_date_of_8fe2da_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinarycase',
            index=models.Index(fields=['case_number'], name='disciplinar_case_nu_0d65d4_idx'),
        ),
    ]
