# Generated by Django 5.0.14 on 2026-05-26 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('REQUEST_MUTATION', 'Mutating Request'), ('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('LOGIN_FAILED', 'Failed Login Attempt'), ('STUDENT_CREATE', 'Student Created'), ('STUDENT_UPDATE', 'Student Updated'), ('STUDENT_DEACTIVATE', 'Student Deactivated'), ('BIOMETRIC_ENROLL', 'Biometric Enrolled'), ('BIOMETRIC_VERIFY_SUCCESS', 'Biometric Verified'), ('BIOMETRIC_VERIFY_FAIL', 'Biometric Failed'), ('CASE_CREATE', 'Case Created'), ('CASE_UPDATE', 'Case Updated'), ('CASE_STATUS_CHANGE', 'Case Status Changed'), ('CASE_DOCUMENT_UPLOAD', 'Document Uploaded'), ('USER_CREATE', 'User Account Created'), ('USER_DEACTIVATE', 'User Account Deactivated'), ('USER_ROLE_CHANGE', 'User Role Changed'), ('REPORT_EXPORT', 'Report Exported')], db_index=True, max_length=50)),
                ('resource_type', models.CharField(blank=True, max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_logs_user_id_88267f_idx'), models.Index(fields=['action', 'timestamp'], name='audit_logs_action_474804_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_logs_resourc_bda8a6_idx')],
            },
        ),
    ]
