# Generated by Django 5.0.14 on 2026-05-26 08:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_hash', models.CharField(max_length=64, unique=True)),
                ('finger_used', models.CharField(default='right_index', max_length=20)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_biometrics', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_template', to='students.student')),
            ],
            options={
                'db_table': 'biometric_templates',
            },
        ),
        migrations.CreateModel(
            name='BiometricVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('ERROR', 'Scanner Error')], max_length=10)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('workstation_id', models.CharField(blank=True, max_length=100)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_attempts', to='students.student')),
            ],
            options={
                'db_table': 'biometric_verification_logs',
                'indexes': [models.Index(fields=['student', 'attempted_at'], name='biometric_v_student_b08448_idx'), models.Index(fields=['result'], name='biometric_v_result_d8ed0c_idx')],
            },
        ),
    ]
